spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/smartdelivery
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate: 
      ddl-auto: update
  rabbitmq: 
      addresses: amqps://ogihosqy:TZCmSUmRwKYU160HDHeJvL-_xSmzaqsI@cougar.rmq.cloudamqp.com/ogihosqy
      username: ogihosqy
      password: TZCmSUmRwKYU160HDHeJvL-_xSmzaqsI
      virtual-host: ogihosqy